# Clippy configuration to allow some warnings while fixing critical issues
[clippy]
# Allow some warnings that are not critical for functionality
allow = [
    "collapsible_if",           # Can be fixed later for readability
    "redundant_closure",        # Minor optimization, not critical
    "needless_range_loop",      # Can be optimized later
    "manual_slice_size_calculation", # Minor optimization
    "manual_is_multiple_of",    # Minor optimization
    "needless_borrow",          # Minor optimization
    "type_complexity",          # Complex types are sometimes necessary
    "new_without_default",      # Not always needed
    "len_zero",                 # Minor style issue
    "needless_question_mark",   # Minor optimization
]
