version: '3.8'

services:
  # Unified Production Service
  vectorizer:
    build:
      context: ..
      dockerfile: devops/docker/Dockerfile
    image: vectorizer:v0.29.0
    container_name: vectorizer-prod
    ports:
      - "15002:15002"  # Unified Server (REST + MCP)
    volumes:
      - vectorizer-data:/app/data
      - vectorizer-cache:/app/cache
      - vectorizer-logs:/app/logs
      - ../config/config.yml:/app/config.yml
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - VECTORIZER_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15002/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s
    networks:
      - vectorizer-network

  # Development Service
  vectorizer-dev:
    build:
      context: ..
      dockerfile: devops/docker/Dockerfile.dev
    image: vectorizer:v0.29.0-dev
    container_name: vectorizer-dev
    ports:
      - "15002:15002"  # Unified Server (REST + MCP)
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - vectorizer-dev-data:/app/data
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - VECTORIZER_ENV=development
    stdin_open: true
    tty: true
    command: bash
    networks:
      - vectorizer-network
    profiles:
      - dev

volumes:
  vectorizer-data:
    driver: local
  vectorizer-cache:
    driver: local
  vectorizer-logs:
    driver: local
  vectorizer-dev-data:
    driver: local
  cargo-cache:
    driver: local

networks:
  vectorizer-network:
    driver: bridge
