/**
 * Schema-evolution + observability API types (phase14).
 *
 * Mirrors the server contract for:
 * - `POST /collections/{name}/rename`
 * - `POST /collections/{name}/reindex`
 * - `POST /collections/{name}/snapshot`
 * - `GET  /collections/{name}/snapshots`
 * - `POST /collections/{name}/snapshots/{id}/restore`
 * - `POST /collections/{name}/explain`
 * - `GET  /slow_queries`
 * - `POST /slow_queries/config`
 *
 * The canonical Rust SDK `src/models.rs` is the source of truth for field names.
 */

// ── Reindex ───────────────────────────────────────────────────────────────────

/**
 * Request body for `reindexCollection`
 * (`POST /collections/{name}/reindex`).
 */
export interface ReindexParams {
  /** HNSW `M` parameter (number of bi-directional links). */
  m: number;
  /** HNSW `ef_construction` (candidate list size during build). */
  ef_construction: number;
  /** HNSW `ef_search` (candidate list size at query time). */
  ef_search: number;
}

/**
 * Job descriptor returned by `reindexCollection`
 * (`POST /collections/{name}/reindex`).
 *
 * Server contract: `{job_id, collection, state, params, progress}`.
 */
export interface ReindexJob {
  /** Opaque job id generated by the server. */
  job_id: string;
  /** Collection that was re-indexed. */
  collection: string;
  /** Job state string (`"completed"` on success). */
  state: string;
  /** HNSW parameters that were applied. */
  params: ReindexParams;
  /** Progress fraction in `[0.0, 1.0]`. */
  progress: number;
}

// ── Native snapshots ──────────────────────────────────────────────────────────

/**
 * Native snapshot metadata returned by `snapshotCollectionNative` and
 * each entry in `listCollectionSnapshotsNative`.
 *
 * Server contract: `{id, collection, created_at, size_bytes}`.
 */
export interface NativeSnapshotInfo {
  /** Opaque snapshot id (UUID string). */
  id: string;
  /** Collection the snapshot was taken from. */
  collection: string;
  /** Creation timestamp in RFC-3339 format. */
  created_at: string;
  /** Compressed snapshot size in bytes. */
  size_bytes: number;
}

// ── Explain search ────────────────────────────────────────────────────────────

/**
 * Execution trace attached to an `ExplainResponse`.
 *
 * Server contract: `{visited_nodes, ef_search, hnsw_search_ms,
 * payload_filter_evals, quantization_score_ms, total_ms}`.
 */
export interface ExplainTrace {
  /** Number of HNSW graph nodes visited during the search. */
  visited_nodes: number;
  /** Effective `ef_search` value used. */
  ef_search: number;
  /** Wall-clock time spent inside HNSW traversal (milliseconds). */
  hnsw_search_ms: number;
  /** Number of payload-filter predicate evaluations. */
  payload_filter_evals: number;
  /** Wall-clock time spent on quantized distance scoring (milliseconds). */
  quantization_score_ms: number;
  /** Total wall-clock time for the explain call (milliseconds). */
  total_ms: number;
}

/**
 * Response from `explainSearch`
 * (`POST /collections/{name}/explain`).
 *
 * Server contract: `{collection, k, results, trace}`.
 */
export interface ExplainResponse {
  /** Collection the search ran against. */
  collection: string;
  /** Number of neighbours requested. */
  k: number;
  /** Ranked search hits (same shape as regular search results). */
  results: Array<{ id: string; score: number; payload: unknown }>;
  /** Full execution trace. */
  trace: ExplainTrace;
}

// ── Slow queries ──────────────────────────────────────────────────────────────

/**
 * One entry in the slow-query ring buffer returned by `GET /slow_queries`.
 *
 * Server contract: `{timestamp, collection, k, duration_ms}`.
 */
export interface SlowQueryEntry {
  /** ISO-8601 / RFC-3339 timestamp when the slow query was recorded. */
  timestamp: string;
  /** Collection the query ran against. */
  collection: string;
  /** Number of neighbours requested (`k`). */
  k: number;
  /** Observed query duration in milliseconds. */
  duration_ms: number;
}

/**
 * Slow-query ring-buffer configuration used as both request body and
 * response for `POST /slow_queries/config`.
 *
 * Server contract: `{threshold_ms, capacity}`.
 */
export interface SlowQueryConfig {
  /** Minimum duration (ms) for a query to be recorded. */
  threshold_ms: number;
  /** Maximum number of entries retained in the ring buffer. */
  capacity: number;
}
