/**
 * Tier-control API report types (phase13).
 *
 * Mirrors the server contract for:
 * - `POST /collections/{name}/vectors/delete_by_filter`
 * - `POST /collections/{name}/vectors/bulk_update_metadata`
 * - `POST /collections/{src}/vectors/copy`
 * - `POST /collections/{name}/reencode`
 * - `POST /collections/{name}/ttl`
 * - `PATCH /collections/{name}/vectors/{id}/expiry`
 *
 * The canonical Rust SDK's `models.rs` is the source of truth for field names.
 */

/**
 * Aggregate outcome of a `deleteByFilter` call against
 * `POST /collections/{name}/vectors/delete_by_filter`.
 *
 * Server contract: `{scanned, matched, deleted, results}`.
 */
export interface DeleteByFilterReport {
  /** Total vectors scanned by the filter pass. */
  scanned: number;
  /** Vectors that matched the filter predicate. */
  matched: number;
  /** Vectors successfully deleted. */
  deleted: number;
  /** Per-id outcomes for matched vectors. */
  results: unknown[];
}

/**
 * Aggregate outcome of a `bulkUpdateMetadata` call against
 * `POST /collections/{name}/vectors/bulk_update_metadata`.
 *
 * Server contract: `{scanned, matched, updated, results}`.
 */
export interface BulkUpdateReport {
  /** Total vectors scanned by the filter pass. */
  scanned: number;
  /** Vectors that matched the filter predicate. */
  matched: number;
  /** Vectors whose metadata was successfully updated. */
  updated: number;
  /** Per-id outcomes for matched vectors. */
  results: unknown[];
}

/**
 * Aggregate outcome of a `copyVectors` call against
 * `POST /collections/{src}/vectors/copy`.
 *
 * Per-id status: `ok | missing_in_src | dst_insert_failed`.
 * Server contract: `{src, dst, requested, copied, failed, results}`.
 */
export interface CopyReport {
  /** Source collection name, echoed by the server. */
  src: string;
  /** Destination collection name, echoed by the server. */
  dst: string;
  /** Total ids the request asked to copy. */
  requested: number;
  /** Successfully copied ids. */
  copied: number;
  /** Ids that failed at any step. */
  failed: number;
  /** Per-id outcomes, in request order. */
  results: CopyOpResult[];
}

/** One row in [[CopyReport.results]]. */
export interface CopyOpResult {
  /** Vector id. */
  id: string | null;
  /** One of: `ok`, `missing_in_src`, `dst_insert_failed`. */
  status: string;
  /** Server-side error message, set when `status !== 'ok'`. */
  error?: string;
}

/**
 * Job descriptor returned by `reencodeCollection` against
 * `POST /collections/{name}/reencode`.
 *
 * Server contract: `{job_id, collection, state, target_encoding, progress}`.
 */
export interface ReencodeJob {
  /** Opaque job id generated by the server. */
  job_id: string;
  /** Collection being re-encoded. */
  collection: string;
  /** Job state string (e.g. `"completed"`). */
  state: string;
  /** Target encoding requested (e.g. `"sq8"`, `"binary"`, `"fp32"`). */
  target_encoding: string;
  /** Progress fraction in `[0.0, 1.0]`. */
  progress: number;
}
