apiVersion: v1
kind: ConfigMap
metadata:
  name: vectorizer-config
  namespace: vectorizer
data:
  config.yml: |
    server:
      host: "0.0.0.0"
      port: 15001
      grpc_port: 15003
      mcp_port: 15002
      mode: "production"
    
    storage:
      persistence_path: "/app/data"
      compression:
        enabled: true
        threshold_bytes: 1024
    
    collections:
      default_dimension: 768
      default_metric: "cosine"
    
    cuda:
      enabled: false
      device_id: 0
      memory_limit_mb: 4096
    
    summarization:
      enabled: true
      default_method: "extractive"
      methods:
        extractive:
          enabled: true
          max_sentences: 5
          lambda: 0.7
        keyword:
          enabled: true
          max_keywords: 10
        sentence:
          enabled: true
          max_sentences: 3
        abstractive:
          enabled: false
          max_length: 200

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vectorizer-workspace
  namespace: vectorizer
data:
  vectorize-workspace.yml: |
    workspace:
      name: "Kubernetes Vectorizer Workspace"
      version: "1.0.0"
      description: "Production workspace for Kubernetes deployment"
    
    global:
      default_embedding:
        model: "bm25"
        dimension: 768
      default_collection:
        metric: "cosine"
        compression:
          enabled: true
          threshold_bytes: 1024
    
    projects:
      - name: "kubernetes-docs"
        path: "/app/data"
        description: "Kubernetes deployment data"
        enabled: true
        collections:
          - name: "documents"
            description: "General documents"
            dimension: 768
            embedding:
              model: "bm25"
              parameters:
                k1: 1.5
                b: 0.75
            processing:
              chunk_size: 2048
              chunk_overlap: 256
