apiVersion: v1
kind: ConfigMap
metadata:
  name: vectorizer-config
  namespace: vectorizer
data:
  config.yml: |
    # Vectorizer v0.29.0 Configuration
    server:
      host: "0.0.0.0"
      port: 15002
      mcp_port: 15003
      mode: "production"
    
    storage:
      persistence_path: "/app/data"
      compression:
        enabled: true
        threshold_bytes: 1024
    
    collections:
      default_dimension: 768
      default_metric: "cosine"
    
    gpu:
      enabled: false
      device_id: 0
      memory_limit_mb: 4096
    
    api:
      rest:
        enabled: true
        cors_enabled: true
      mcp:
        enabled: true
        sse_enabled: true
    
    performance:
      cpu:
        threads: 4
        batch_size: 100
      batch:
        max_size: 1000
        timeout_ms: 5000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vectorizer-workspace
  namespace: vectorizer
data:
  vectorize-workspace.yml: |
    workspace:
      name: "Kubernetes Vectorizer Workspace"
      version: "1.0.0"
      description: "Production workspace for Kubernetes deployment"
    
    global:
      default_embedding:
        model: "bm25"
        dimension: 768
      default_collection:
        metric: "cosine"
        compression:
          enabled: true
          threshold_bytes: 1024
    
    projects:
      - name: "kubernetes-docs"
        path: "/app/data"
        description: "Kubernetes deployment data"
        enabled: true
        collections:
          - name: "documents"
            description: "General documents"
            dimension: 768
            embedding:
              model: "bm25"
              parameters:
                k1: 1.5
                b: 0.75
            processing:
              chunk_size: 2048
              chunk_overlap: 256
