apiVersion: v1
kind: Service
metadata:
  name: vectorizer-service
  namespace: vectorizer
  labels:
    app: vectorizer
spec:
  type: ClusterIP
  ports:
  - port: 15001
    targetPort: 15001
    protocol: TCP
    name: rest-api
  - port: 15002
    targetPort: 15002
    protocol: TCP
    name: mcp-server
  - port: 15003
    targetPort: 15003
    protocol: TCP
    name: grpc-server
  selector:
    app: vectorizer

---
apiVersion: v1
kind: Service
metadata:
  name: vectorizer-service-nodeport
  namespace: vectorizer
  labels:
    app: vectorizer
spec:
  type: NodePort
  ports:
  - port: 15001
    targetPort: 15001
    nodePort: 30001
    protocol: TCP
    name: rest-api
  - port: 15002
    targetPort: 15002
    nodePort: 30002
    protocol: TCP
    name: mcp-server
  - port: 15003
    targetPort: 15003
    nodePort: 30003
    protocol: TCP
    name: grpc-server
  selector:
    app: vectorizer

---
apiVersion: v1
kind: Service
metadata:
  name: vectorizer-service-loadbalancer
  namespace: vectorizer
  labels:
    app: vectorizer
spec:
  type: LoadBalancer
  ports:
  - port: 15001
    targetPort: 15001
    protocol: TCP
    name: rest-api
  - port: 15002
    targetPort: 15002
    protocol: TCP
    name: mcp-server
  - port: 15003
    targetPort: 15003
    protocol: TCP
    name: grpc-server
  selector:
    app: vectorizer
