# Vectorizer Workspace Configuration
# This file defines multiple projects and their configurations for the Vectorizer system.
# Copy this file to vectorize-workspace.yml and customize according to your needs.

# =============================================================================
# WORKSPACE METADATA
# =============================================================================
workspace:
  name: "HiveLLM Development Workspace"
  version: "1.0.0"
  description: "Multi-project workspace for HiveLLM ecosystem development"
  created_at: "2024-01-01T00:00:00Z"
  last_updated: "2024-01-01T00:00:00Z"

# =============================================================================
# GLOBAL SETTINGS
# =============================================================================
global:
  # Default embedding configuration for all projects
  default_embedding:
    model: "native_bow"           # native_bow, native_hash, native_ngram, bm25, real_model, onnx_model
    dimension: 384                 # Vector dimension (384, 768, etc.)
    parameters:
      vocab_size: 50000
      max_sequence_length: 512
  
  # Default collection settings
  default_collection:
    metric: "cosine"               # cosine, euclidean, dot_product
    compression:
      enabled: true
      threshold_bytes: 1024
      algorithm: "lz4"
  
  # Default indexing settings
  default_indexing:
    type: "hnsw"
    parameters:
      m: 16
      ef_construction: 200
      ef_search: 64
  
  # Processing settings
  processing:
    chunk_size: 512
    chunk_overlap: 50
    max_file_size_mb: 10
    supported_extensions:
      - ".md"
      - ".txt"
      - ".rs"
      - ".py"
      - ".js"
      - ".ts"
      - ".json"
      - ".yaml"
      - ".yml"
      - ".toml"

# =============================================================================
# PROJECT CONFIGURATIONS
# =============================================================================
projects:
  # Governance Project (BIP Specs)
  - name: "governance-bip-specs"
    path: "../gov"
    description: "🏛️ Governance (BIP Specs) - HiveLLM Governance System with BIPs, proposals, and voting"
    enabled: true
    
    # Project-specific embedding configuration
    embedding:
      model: "bm25"               # Override global default
      dimension: 768               # Higher dimension for governance docs
      parameters:
        k1: 1.5
        b: 0.75
    
    # Collections for this project
    collections:
      - name: "bips"
        description: "Blockchain Improvement Proposals"
        dimension: 768
        metric: "cosine"
        embedding:
          model: "bm25"
          parameters:
            k1: 1.5
            b: 0.75
        indexing:
          type: "hnsw"
          parameters:
            m: 16
            ef_construction: 200
            ef_search: 64
        processing:
          chunk_size: 1024
          chunk_overlap: 100
          include_patterns:
            - "bips/**/*.md"
            - "bips/**/*.txt"
          exclude_patterns:
            - "bips/**/README.md"
      
      - name: "proposals"
        description: "Governance proposals and voting records"
        dimension: 384
        metric: "cosine"
        embedding:
          model: "native_bow"
          parameters:
            vocab_size: 100000
        processing:
          chunk_size: 512
          chunk_overlap: 50
          include_patterns:
            - "proposals/**/*.md"
            - "proposals/**/*.json"
      
      - name: "minutes"
        description: "Governance meeting minutes"
        dimension: 384
        metric: "cosine"
        embedding:
          model: "native_bow"
        processing:
          chunk_size: 256
          chunk_overlap: 25
          include_patterns:
            - "minutes/**/*.md"
            - "minutes/**/*.json"

  # Governance Dashboard Project
  - name: "governance-dashboard"
    path: "../governance"
    description: "🏛️ Governance Dashboard - Implementation of the governance system"
    enabled: true
    
    embedding:
      model: "real_model"
      dimension: 384
      parameters:
        model_type: "MiniLMMultilingual"
        cache_dir: "./models"
    
    collections:
      - name: "source_code"
        description: "Governance dashboard source code"
        dimension: 384
        metric: "cosine"
        embedding:
          model: "real_model"
          parameters:
            model_type: "MiniLMMultilingual"
        processing:
          chunk_size: 256
          chunk_overlap: 25
          include_patterns:
            - "src/**/*.ts"
            - "src/**/*.js"
            - "src/**/*.json"
          exclude_patterns:
            - "src/**/node_modules/**"
            - "src/**/dist/**"
            - "src/**/*.d.ts"
      
      - name: "configurations"
        description: "Configuration files and schemas"
        dimension: 384
        metric: "cosine"
        embedding:
          model: "native_bow"
        processing:
          chunk_size: 128
          chunk_overlap: 10
          include_patterns:
            - "**/*.json"
            - "**/*.yml"
            - "**/*.yaml"
            - "**/*.toml"
            - "**/*.env*"

  # TypeScript Workspace Project (BIP-01,02,03)
  - name: "ts-workspace"
    path: "../ts-workspace"
    description: "🔷 TypeScript (BIP-01,02,03) - TypeScript development workspace with packages"
    enabled: true
    
    embedding:
      model: "native_ngram"
      dimension: 384
      parameters:
        ngram_range: [1, 3]
        vocab_size: 100000
    
    collections:
      - name: "packages"
        description: "TypeScript packages and modules"
        dimension: 384
        metric: "cosine"
        embedding:
          model: "native_ngram"
          parameters:
            ngram_range: [1, 3]
            vocab_size: 100000
        processing:
          chunk_size: 256
          chunk_overlap: 25
          include_patterns:
            - "packages/**/*.ts"
            - "packages/**/*.js"
            - "packages/**/*.json"
          exclude_patterns:
            - "packages/**/node_modules/**"
            - "packages/**/dist/**"
            - "packages/**/*.d.ts"
      
      - name: "documentation"
        description: "Project documentation and guides"
        dimension: 384
        metric: "cosine"
        embedding:
          model: "native_bow"
        processing:
          chunk_size: 512
          chunk_overlap: 50
          include_patterns:
            - "**/*.md"
            - "docs/**/*.md"

  # Governance System Project
  - name: "governance-system"
    path: "../governance"
    description: "Governance system implementation"
    enabled: true
    
    embedding:
      model: "real_model"
      dimension: 384
      parameters:
        model_type: "MiniLMMultilingual"
        cache_dir: "./models"
    
    collections:
      - name: "source_code"
        description: "Governance system source code"
        dimension: 384
        metric: "cosine"
        embedding:
          model: "real_model"
          parameters:
            model_type: "MiniLMMultilingual"
        processing:
          chunk_size: 256
          chunk_overlap: 25
          include_patterns:
            - "src/**/*.ts"
            - "src/**/*.js"
            - "src/**/*.json"
          exclude_patterns:
            - "src/**/node_modules/**"
            - "src/**/dist/**"
            - "src/**/*.d.ts"
      
      - name: "configurations"
        description: "Configuration files and schemas"
        dimension: 384
        metric: "cosine"
        embedding:
          model: "native_bow"
        processing:
          chunk_size: 128
          chunk_overlap: 10
          include_patterns:
            - "**/*.json"
            - "**/*.yml"
            - "**/*.yaml"
            - "**/*.toml"
            - "**/*.env*"

  # Cursor Extension Project (BIP-00)
  - name: "cursor-extension"
    path: "../cursor-extension"
    description: "🎯 Cursor Extension (BIP-00) - Cursor IDE extension for HiveLLM"
    enabled: true
    
    embedding:
      model: "onnx_model"
      dimension: 384
      parameters:
        model_type: "MiniLMMultilingual384"
        batch_size: 128
        use_int8: true
    
    collections:
      - name: "extension_code"
        description: "Extension source code and implementation"
        dimension: 384
        metric: "cosine"
        embedding:
          model: "onnx_model"
          parameters:
            model_type: "MiniLMMultilingual384"
        processing:
          chunk_size: 256
          chunk_overlap: 25
          include_patterns:
            - "src/**/*.ts"
            - "src/**/*.js"
            - "packages/**/*.ts"
            - "packages/**/*.js"
          exclude_patterns:
            - "**/node_modules/**"
            - "**/dist/**"
            - "**/*.d.ts"
      
      - name: "scripts"
        description: "Build and utility scripts"
        dimension: 384
        metric: "cosine"
        embedding:
          model: "native_bow"
        processing:
          chunk_size: 128
          chunk_overlap: 10
          include_patterns:
            - "scripts/**/*.py"
            - "scripts/**/*.sh"
            - "scripts/**/*.js"

  # Security Environment Project (BIP-04)
  - name: "py-env-security"
    path: "../py-env-security"
    description: "🔒 Security Environment (BIP-04) - Python security environment and tools"
    enabled: true
    
    embedding:
      model: "native_hash"
      dimension: 512
      parameters:
        hash_size: 1000000
    
    collections:
      - name: "security_tools"
        description: "Security analysis and audit tools"
        dimension: 512
        metric: "cosine"
        embedding:
          model: "native_hash"
          parameters:
            hash_size: 1000000
        processing:
          chunk_size: 256
          chunk_overlap: 25
          include_patterns:
            - "**/*.py"
            - "**/*.md"
          exclude_patterns:
            - "**/__pycache__/**"
            - "**/tests/**"
      
      - name: "documentation"
        description: "Security documentation and guides"
        dimension: 512
        metric: "cosine"
        embedding:
          model: "native_bow"
        processing:
          chunk_size: 512
          chunk_overlap: 50
          include_patterns:
            - "docs/**/*.md"
            - "**/*.md"

  # UMICP Project (BIP-05)
  - name: "umicp"
    path: "../umicp"
    description: "🌐 UMICP Protocol (BIP-05) - Universal Matrix Inter-Communication Protocol"
    enabled: true
    
    embedding:
      model: "bm25"
      dimension: 768
      parameters:
        k1: 1.5
        b: 0.75
    
    collections:
      - name: "protocol_spec"
        description: "UMICP protocol specification and documentation"
        dimension: 768
        metric: "cosine"
        embedding:
          model: "bm25"
          parameters:
            k1: 1.5
            b: 0.75
        processing:
          chunk_size: 1024
          chunk_overlap: 100
          include_patterns:
            - "docs/**/*.md"
            - "docs/**/*.html"
            - "docs/**/*.js"
      
      - name: "implementations"
        description: "UMICP implementations in different languages"
        dimension: 768
        metric: "cosine"
        embedding:
          model: "bm25"
        processing:
          chunk_size: 256
          chunk_overlap: 25
          include_patterns:
            - "bindings/**/*.rs"
            - "bindings/**/*.ts"
            - "cpp/**/*.cpp"
            - "cpp/**/*.h"
          exclude_patterns:
            - "**/build/**"
            - "**/target/**"

  # Chat Hub Project
  - name: "chat-hub"
    path: "../chat-hub"
    description: "💬 Chat Hub & Monitoring - Centralized chat hub for HiveLLM ecosystem"
    enabled: true
    
    embedding:
      model: "real_model"
      dimension: 384
      parameters:
        model_type: "MiniLMMultilingual"
    
    collections:
      - name: "server_code"
        description: "Chat hub server implementation"
        dimension: 384
        metric: "cosine"
        embedding:
          model: "real_model"
          parameters:
            model_type: "MiniLMMultilingual"
        processing:
          chunk_size: 256
          chunk_overlap: 25
          include_patterns:
            - "**/*.js"
            - "**/*.json"
            - "**/*.html"
          exclude_patterns:
            - "**/node_modules/**"
      
      - name: "scripts"
        description: "Utility scripts and tools"
        dimension: 384
        metric: "cosine"
        embedding:
          model: "native_bow"
        processing:
          chunk_size: 128
          chunk_overlap: 10
          include_patterns:
            - "scripts/**/*.js"

# =============================================================================
# WORKSPACE PROCESSING SETTINGS
# =============================================================================
processing:
  # Global processing settings
  parallel_processing: true
  max_concurrent_projects: 4
  max_concurrent_collections: 8
  
  # File processing
  file_processing:
    batch_size: 100
    max_file_size_mb: 10
    skip_hidden_files: true
    skip_binary_files: true
    
  # Memory management
  memory:
    max_memory_usage_gb: 8.0
    gc_threshold_mb: 1024
    
  # Error handling
  error_handling:
    max_retries: 3
    retry_delay_seconds: 5
    continue_on_error: true
    log_errors: true

# =============================================================================
# WORKSPACE MONITORING
# =============================================================================
monitoring:
  # Health checks
  health_check:
    enabled: true
    interval_seconds: 60
    check_projects: true
    check_collections: true
  
  # Metrics collection
  metrics:
    enabled: true
    collection_interval_seconds: 300
    
    # Metrics to collect
    project_metrics:
      - file_count
      - total_size_mb
      - processing_time_seconds
      - error_count
    
    collection_metrics:
      - vector_count
      - index_size_mb
      - query_latency_ms
      - memory_usage_mb
  
  # Logging
  logging:
    level: "info"
    log_file: "./logs/workspace.log"
    max_log_size_mb: 100
    max_log_files: 5

# =============================================================================
# WORKSPACE VALIDATION
# =============================================================================
validation:
  # Path validation
  paths:
    validate_existence: true
    validate_permissions: true
    create_missing_dirs: false
  
  # Configuration validation
  config:
    validate_embedding_models: true
    validate_dimensions: true
    validate_collections: true
  
  # Data validation
  data:
    validate_file_types: true
    validate_file_sizes: true
    validate_encoding: true

---
# Configuration Notes:
#
# 1. All paths are relative to the workspace root directory
# 2. Project paths are relative to the vectorizer directory
# 3. Embedding models: native_bow, native_hash, native_ngram, bm25, real_model, onnx_model
# 4. Dimensions: 384 (fast), 768 (balanced), 1536 (high-quality)
# 5. Metrics: cosine (recommended), euclidean, dot_product
# 6. Indexing: hnsw (recommended), optimized_hnsw
#
# Usage:
#   vectorizer workspace --config vectorize-workspace.yml
#   vectorizer workspace --validate
#   vectorizer workspace --status
#
# Validation:
#   The workspace configuration is validated on startup
#   Invalid configurations will prevent workspace loading with detailed error messages
