# Vectorizer Workspace Configuration for Docker
# This file maps the monorepo paths for Docker container usage
# Host path ../../ is mounted as /workspace in the container

global_settings:
  file_watcher:
    auto_discovery: true
    enable_auto_update: true
    exclude_patterns: []
    hot_reload: true
    watch_paths:
      - /workspace  # Root of the monorepo

# Note: All paths here are INSIDE the Docker container
# Host: ../../cmmv/cmmv → Container: /workspace/cmmv/cmmv
# Host: ../../hivellm/vectorizer → Container: /workspace/hivellm/vectorizer

projects:
  # HiveLLM Projects
  - name: vectorizer
    path: /workspace/hivellm/vectorizer
    description: Vectorizer - Vector database and search engine
    collections:
      - name: vectorizer-source
        description: Vectorizer Rust source code
        include_patterns:
          - "src/**/*.rs"
          - "**/*.toml"
          - "build.rs"
        exclude_patterns:
          - "target/**"
          - "data/**"
          - "logs/**"
      
      - name: vectorizer-docs
        description: Vectorizer documentation
        include_patterns:
          - "docs/**/*.md"
          - "*.md"
        exclude_patterns:
          - "target/**"

  - name: governance
    path: /workspace/hivellm/governance
    description: Governance System - Project management
    collections:
      - name: governance-source
        description: Governance TypeScript source code
        include_patterns:
          - "src/**/*.ts"
          - "src/**/*.js"
          - "**/*.json"
          - "scripts/**/*"
        exclude_patterns:
          - "node_modules/**"
          - "dist/**"
          - "*.db*"
      
      - name: governance-docs
        description: Governance documentation
        include_patterns:
          - "*.md"
          - "views/**/*.md"
        exclude_patterns:
          - "node_modules/**"

  - name: task-queue
    path: /workspace/hivellm/task-queue
    description: Task Queue - Distributed task processing
    collections:
      - name: task-queue-source
        description: Task Queue Rust source code
        include_patterns:
          - "src/**/*.rs"
          - "cli/**/*.rs"
          - "**/*.toml"
        exclude_patterns:
          - "target/**"
          - "data/**"

  # CMMV Projects
  - name: cmmv-core
    path: /workspace/cmmv/cmmv
    description: CMMV Core - Main framework
    collections:
      - name: cmmv-core-source
        description: CMMV Core source code
        include_patterns:
          - "src/**/*.ts"
          - "packages/**/*.ts"
          - "packages/**/*.js"
          - "**/*.json"
        exclude_patterns:
          - "node_modules/**"
          - "packages/**/node_modules/**"
          - "**/*.map"
      
      - name: cmmv-core-docs
        description: CMMV Core documentation
        include_patterns:
          - "*.md"
          - "i18n/**/*.md"
        exclude_patterns:
          - "node_modules/**"

  - name: cmmv-ai
    path: /workspace/cmmv/cmmv-ai
    description: CMMV AI - Artificial Intelligence integration
    collections:
      - name: cmmv-ai-source
        description: CMMV AI source code
        include_patterns:
          - "src/**/*.ts"
          - "src/**/*.py"
          - "**/*.json"
        exclude_patterns:
          - "node_modules/**"
          - "dist/**"

# Add more CMMV projects as needed following the pattern above
# Just replace ../../cmmv/cmmv-* with /workspace/cmmv/cmmv-*

