//! tonic/prost-generated gRPC types for Vectorizer.
//!
//! Relocated out of `vectorizer-protocol` so that crate's RPC-wire layer can
//! move to `thunder-rpc` and be deleted. This crate carries only the gRPC
//! side: the three schemas below, generated by this crate's `build.rs` against
//! the `proto/` source tree. It is an internal workspace crate (consumed by
//! `vectorizer` + `vectorizer-server`) and is not published to crates.io.
//!
//! - [`grpc_gen::vectorizer`]     — first-party `VectorizerService`
//! - [`grpc_gen::cluster`]        — inter-node `ClusterService` (incl. Raft)
//! - [`grpc_gen::qdrant_proto`]   — Qdrant-compatible services

#![deny(missing_docs)]

/// `tonic-prost`-generated gRPC modules. Mirrors the layout of the
/// underlying `proto/` source tree.
///
/// Generated code can't carry per-item lint annotations, so the
/// wrapping module silences the workspace lints that the proto
/// generator routinely trips (large enum variants from one-of
/// fields, `#[non_exhaustive]` boilerplate, missing docs).
#[allow(
    missing_docs,
    clippy::large_enum_variant,
    clippy::doc_markdown,
    clippy::module_inception
)]
pub mod grpc_gen {
    /// First-party Vectorizer gRPC schema (`proto/vectorizer.proto`).
    pub mod vectorizer {
        include!("grpc_gen/vectorizer.rs");
    }

    /// Cluster RPC schema (`proto/cluster.proto`).
    pub mod cluster {
        include!("grpc_gen/vectorizer.cluster.rs");
    }

    /// Qdrant compatibility schema (`proto/qdrant/*.proto`).
    pub mod qdrant_proto {
        include!("grpc_gen/qdrant/qdrant.rs");
    }
}
